steps:
  - name: rust:1.90-bullseye # Debian 11, GLIBC 2.31
    entrypoint: bash
    args:
      - -c
      - |
        cargo build --release

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        TIMESTAMP=$$(date +%Y%m%d%H%M%S)
        # Upload both versioned and latest
        gsutil cp target/release/near-defuse-indexer gs://near-indexer-builds/near-defuse-indexer-$${TIMESTAMP}
        gsutil cp target/release/near-defuse-indexer gs://near-indexer-builds/near-defuse-indexer
        gsutil cp target/release/indexer-explorer gs://near-indexer-builds/indexer-explorer-$${TIMESTAMP}
        gsutil cp target/release/indexer-explorer gs://near-indexer-builds/indexer-explorer

options:
  logging: CLOUD_LOGGING_ONLY
  # Use a larger machine for faster Rust release builds.
  # Available examples: E2_HIGHCPU_8, E2_HIGHCPU_16, E2_HIGHCPU_32, E2_STANDARD_32, etc.
  machineType: E2_HIGHCPU_8

artifacts:
  objects:
    location: gs://near-indexer-builds/
    paths: ["target/release/near-defuse-indexer", "target/release/indexer-explorer"]
