version: '3.8'

services:
  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"     # Jaeger UI
      - "14268:14268"     # HTTP collector for spans (legacy)
      - "14250:14250"     # gRPC collector
      - "4317:4317"       # OTLP gRPC
      - "4318:4318"       # OTLP HTTP
      - "6831:6831/udp"   # UDP port for jaeger-agent
      - "6832:6832/udp"   # UDP port for jaeger-agent
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - tracing

  # Alternative: OpenObserve for observability
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    ports:
      - "5080:5080"       # OpenObserve UI and API
    environment:
      - ZO_ROOT_USER_EMAIL=admin@example.com
      - ZO_ROOT_USER_PASSWORD=admin123
      - ZO_DATA_DIR=/data
    volumes:
      - openobserve_data:/data
    networks:
      - tracing

networks:
  tracing:
    driver: bridge

volumes:
  openobserve_data:
